# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: miner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'miner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bminer.proto\"\x07\n\x05\x45mpty\"-\n\x14TransactionIDRequest\x12\x15\n\rtransactionID\x18\x01 \x01(\x05\".\n\x15TransactionIDResponse\x12\x15\n\rtransactionID\x18\x01 \x01(\x05\"&\n\x11\x43hallengeResponse\x12\x11\n\tchallenge\x18\x01 \x01(\x05\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"L\n\x0fSolutionRequest\x12\x15\n\rtransactionID\x18\x01 \x01(\x05\x12\x10\n\x08\x63lientID\x18\x02 \x01(\x05\x12\x10\n\x08solution\x18\x03 \x01(\t\" \n\x0eSubmitResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\"\n\x0eWinnerResponse\x12\x10\n\x08winnerID\x18\x01 \x01(\x05\"K\n\x14SolutionInfoResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08solution\x18\x02 \x01(\t\x12\x11\n\tchallenge\x18\x03 \x01(\x05\x32\xea\x02\n\x05Miner\x12\x34\n\x10getTransactionID\x12\x06.Empty\x1a\x16.TransactionIDResponse\"\x00\x12;\n\x0cgetChallenge\x12\x15.TransactionIDRequest\x1a\x12.ChallengeResponse\"\x00\x12@\n\x14getTransactionStatus\x12\x15.TransactionIDRequest\x1a\x0f.StatusResponse\"\x00\x12\x36\n\x0fsubmitChallenge\x12\x10.SolutionRequest\x1a\x0f.SubmitResponse\"\x00\x12\x35\n\tgetWinner\x12\x15.TransactionIDRequest\x1a\x0f.WinnerResponse\"\x00\x12=\n\x0bgetSolution\x12\x15.TransactionIDRequest\x1a\x15.SolutionInfoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'miner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=15
  _globals['_EMPTY']._serialized_end=22
  _globals['_TRANSACTIONIDREQUEST']._serialized_start=24
  _globals['_TRANSACTIONIDREQUEST']._serialized_end=69
  _globals['_TRANSACTIONIDRESPONSE']._serialized_start=71
  _globals['_TRANSACTIONIDRESPONSE']._serialized_end=117
  _globals['_CHALLENGERESPONSE']._serialized_start=119
  _globals['_CHALLENGERESPONSE']._serialized_end=157
  _globals['_STATUSRESPONSE']._serialized_start=159
  _globals['_STATUSRESPONSE']._serialized_end=191
  _globals['_SOLUTIONREQUEST']._serialized_start=193
  _globals['_SOLUTIONREQUEST']._serialized_end=269
  _globals['_SUBMITRESPONSE']._serialized_start=271
  _globals['_SUBMITRESPONSE']._serialized_end=303
  _globals['_WINNERRESPONSE']._serialized_start=305
  _globals['_WINNERRESPONSE']._serialized_end=339
  _globals['_SOLUTIONINFORESPONSE']._serialized_start=341
  _globals['_SOLUTIONINFORESPONSE']._serialized_end=416
  _globals['_MINER']._serialized_start=419
  _globals['_MINER']._serialized_end=781
# @@protoc_insertion_point(module_scope)
